GTI619_Lab5/Controllers/CircleController.cs
using GTI619_Lab5.Entities;
using GTI619_Lab5.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Web.Mvc;
using static GTI619_Lab5.Controllers.AccountController;

namespace GTI619_Lab5.Controllers
{
    public class CircleController : Controller
    {
        private ApplicationDbContext _context;
        public UserManager<ApplicationUser> UserManager { get; private set; }

        public CircleController()
        {
            _context = new ApplicationDbContext();
            UserManager = new MyUserManager(new UserStore<ApplicationUser>(_context));
        }

        //
        // GET: /Circle/
        [Authorize(Roles = "Cercle, Administrateur")]
        public ActionResult Index()
        {
            if (UserManager.FindById(User.Identity.GetUserId()).NeedNewPassword)
            {
                return RedirectToAction("Manage", "Account", new { Message = ManageMessageId.HaveToChange });
            }

            return View();
        }
	}
}

GTI619_Lab5/Controllers/SquareController.cs
using GTI619_Lab5.Entities;
using GTI619_Lab5.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static GTI619_Lab5.Controllers.AccountController;

namespace GTI619_Lab5.Controllers
{
    public class SquareController : Controller
    {
        private ApplicationDbContext _context;
        public UserManager<ApplicationUser> UserManager { get; private set; }

        public SquareController()
        {
            _context = new ApplicationDbContext();
            UserManager = new MyUserManager(new UserStore<ApplicationUser>(_context));
        }

        //
        // GET: /Square/
        [Authorize(Roles = "Carrée, Administrateur")]
        public ActionResult Index()
        {
            if (UserManager.FindById(User.Identity.GetUserId()).NeedNewPassword)
            {
                return RedirectToAction("Manage", "Account", new { Message = ManageMessageId.HaveToChange });
            }

            return View();
        }
	}
}

GTI619_Lab5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nom de l'application", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
                    <li>@Html.ActionLink("À propos de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    @if (User.IsInRole("Cercle") || User.IsInRole("Administrateur"))
                    {
                        <li>@Html.ActionLink("Cercle", "Index", "Circle")</li>
                    }
                    @if (User.IsInRole("Carrée") || User.IsInRole("Administrateur"))
                    {
                        <li>@Html.ActionLink("Carrée", "Index", "Square")</li>
                    }
                    @if (User.IsInRole("Administrateur"))
                    {
                        <li>@Html.ActionLink("Admin", "Manage", "Admin")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>